-- AlterTable
ALTER TABLE `users` ADD COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `delete_at` DATETIME(3) NULL,
    ADD COLUMN `updated_at` DATETIME(3) NULL;
